# Generated by Django 5.0.2 on 2024-02-27 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время старта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость продукта')),
                ('min_students', models.IntegerField(default=1, verbose_name='Минимальное количество студентов')),
                ('max_students', models.IntegerField(default=30, verbose_name='Максимальное количество студентов')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Связь с создателем продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название урока')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferst.product', verbose_name='Связь с продуктом')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название группы')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferst.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ferst.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
