# Generated by Django 5.0.2 on 2024-03-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferst', '0003_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lesson_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество уроков'),
        ),
    ]
